apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: maw7ajtjh-nodejs
  janus-idp.io/tekton: maw7ajtjh-nodejs
  backstage.io/kubernetes-id: maw7ajtjh-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: maw7ajtjh-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
